// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type NewSurvey struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Question    string `json:"question"`
}

type NewSurveyResponse struct {
	SurveyID string `json:"surveyId"`
	Answers  string `json:"answers"`
	Rating   int    `json:"rating"`
}

type Survey struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Question    string    `json:"question"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type SurveyResponse struct {
	ID        string    `json:"id"`
	Survey    *Survey   `json:"survey"`
	Answer    string    `json:"answer"`
	Rating    int       `json:"rating"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
