package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"

	"github.com/jbactad/loop/graph/generated"
	"github.com/jbactad/loop/graph/models"
)

// SurveyCreated is the resolver for the surveyCreated field.
func (r *subscriptionResolver) SurveyCreated(ctx context.Context) (<-chan *models.Survey, error) {
	panic(fmt.Errorf("not implemented: SurveyCreated - surveyCreated"))
}

// SurveyResponseCreated is the resolver for the surveyResponseCreated field.
func (r *subscriptionResolver) SurveyResponseCreated(ctx context.Context) (<-chan *models.SurveyResponse, error) {
	panic(fmt.Errorf("not implemented: SurveyResponseCreated - surveyResponseCreated"))
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
